name: nova_wheels
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_ui:
    path: packages/app_ui
  shared:
    path: packages/shared

  flutter_local_notifications: ^17.2.1+2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  equatable: 2.0.5
  get_it: ^7.7.0
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0
  shared_preferences: ^2.3.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  go_router: ^14.2.2
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3
  image_picker: ^1.1.2
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  dropdown_button2: ^2.3.9
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  firebase_messaging: ^15.0.4
  internet_connection_checker_plus: ^2.5.1
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.0
  supabase_flutter: ^2.5.11
  jiffy: ^6.3.1
  blurhash: ^1.1.1
  flutter_image_compress: ^2.3.0
  timeago: ^3.7.0
  google_nav_bar: ^5.0.6
  firebase_core: ^3.3.0
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.0
  flutter_cache_manager: ^3.4.1
  sqflite: ^2.3.3+1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - lib/features/landing/presentation/assets/image/
    - lib/features/sign_in/presentation/assets/svg/

