name: nova_wheels
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
#  integration_test: ^1.0.2+3
  app_ui:
    path: packages/app_ui
  shared:
    path: packages/shared

  dotted_border: ^2.0.0
  flutter_local_notifications: ^17.2.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  equatable: 2.0.5
  get_it: ^7.7.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  go_router: ^14.2.7
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3+1
  image_picker: ^1.1.2
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  dropdown_button2: ^2.3.9
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  firebase_messaging: ^15.1.2
  internet_connection_checker_plus: ^2.5.2
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.0
  supabase_flutter: ^2.6.0
  jiffy: ^6.3.1
  blurhash: ^1.1.1
  flutter_image_compress: ^2.3.0
  timeago: ^3.7.0
  google_nav_bar: ^5.0.6
  firebase_core: ^3.5.0
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  sqflite: ^2.3.3+1
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  skeletonizer: ^1.4.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  bloc_concurrency: ^0.2.5
  persistent_bottom_nav_bar: ^6.2.1
  google_fonts: ^6.2.1
  flutter_gemini: ^2.0.5
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  mocktail: ^1.0.4
  patrol: ^3.13.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0

patrol:
    app_name: nova_wheels
    android:
      package_name: com.example.nova_wheels

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700



  assets:
    - .env
    - lib/core/base_component/lottie/
    - lib/features/landing/presentation/assets/image/
    - lib/features/sign_in/presentation/assets/svg/
    - lib/features/onboarding/presentation/asset/lottie_animation/
    - lib/core/base_component/logo/png/
    - lib/core/base_component/logo/svg/


